---
# Example Versioning Scheme for Test Plan Data Configuration
# This demonstrates how to organize specs and test plans by version

version: "2.0"
last_updated: "2025-09-09"
description: "Repository with versioned technology specifications and test plans"

# Example 1: NVMe with multiple versions
nvme:
  category: "storage"
  description: "NVMe (Non-Volatile Memory Express) specifications and conformance test plans"
  
  versions:
    # NVMe 1.3
    "1.3":
      base_spec:
        name: "NVMe Base Specification 1.3"
        file: "specs/nvme/1.3/NVMe-1.3d.pdf"
        ratified: "2019-03-20"
        pages: 358
      
      command_sets:
        nvm:
          spec:
            name: "NVM Command Set Specification 1.0"
            file: "specs/nvme/1.3/NVM-Command-Set-1.0.pdf"
            pages: 98
          test_plans:
            - name: "NVM Command Set Conformance"
              file: "testplans/nvme/1.3/NVM-Command-Set-Conformance-v1.3.pdf"
              organization: "UNH-IOL"
              pages: 496
      
      transports:
        pcie:
          spec:
            name: "NVMe over PCIe Transport 1.3"
            file: "specs/nvme/1.3/NVMe-over-PCIe-1.3.pdf"
            pages: 38
          test_plans:
            - name: "PCIe Transport Conformance"
              file: "testplans/nvme/1.3/PCIe-Transport-Conformance-v1.3.pdf"
              pages: 28
    
    # NVMe 1.4
    "1.4":
      base_spec:
        name: "NVMe Base Specification 1.4"
        file: "specs/nvme/1.4/NVMe-1.4b.pdf"
        ratified: "2020-09-21"
        pages: 403
      
      command_sets:
        nvm:
          spec:
            name: "NVM Command Set Specification 1.0a"
            file: "specs/nvme/1.4/NVM-Command-Set-1.0a.pdf"
            pages: 112
          test_plans:
            - name: "NVM Command Set Conformance"
              file: "testplans/nvme/1.4/NVM-Command-Set-Conformance-v1.4.pdf"
              organization: "UNH-IOL"
              pages: 512
        
        zns:
          spec:
            name: "Zoned Namespace Command Set 1.0"
            file: "specs/nvme/1.4/ZNS-Command-Set-1.0.pdf"
            pages: 45
          test_plans:
            - name: "ZNS Command Set Conformance"
              file: "testplans/nvme/1.4/ZNS-Conformance-v1.4.pdf"
              pages: 132
      
      transports:
        pcie:
          spec:
            name: "NVMe over PCIe Transport 1.4"
            file: "specs/nvme/1.4/NVMe-over-PCIe-1.4.pdf"
            pages: 42
          test_plans:
            - name: "PCIe Transport Conformance"
              file: "testplans/nvme/1.4/PCIe-Transport-Conformance-v1.4.pdf"
              pages: 32
        
        fabrics:
          spec:
            name: "NVMe over Fabrics 1.1"
            file: "specs/nvme/1.4/NVMe-over-Fabrics-1.1.pdf"
            pages: 82
          test_plans:
            - name: "RDMA Transport Conformance"
              file: "testplans/nvme/1.4/RDMA-Transport-Conformance-v1.4.pdf"
              pages: 38
            - name: "TCP Transport Conformance"
              file: "testplans/nvme/1.4/TCP-Transport-Conformance-v1.4.pdf"
              pages: 65
    
    # NVMe 2.0
    "2.0":
      base_spec:
        name: "NVMe Base Specification 2.0c"
        file: "specs/nvme/2.0/NVMe-2.0c.pdf"
        ratified: "2023-06-13"
        pages: 485
      
      command_sets:
        nvm:
          spec:
            name: "NVM Command Set Specification 1.2"
            file: "specs/nvme/2.0/NVM-Express-NVM-Command-Set-Specification-Revision-1.2-2025.08.01-Ratified.pdf"
            pages: 158
          test_plans:
            - name: "NVM Command Set Conformance"
              file: "testplans/nvme/2.0/NVM-Command-Set-Conformance-v23.0.pdf"
              version: "23.0"
              organization: "UNH-IOL"
              pages: 496
        
        zns:
          spec:
            name: "Zoned Namespace Command Set 1.4"
            file: "specs/nvme/2.0/NVM-Express-Zoned-Namespace-Command-Set-Specification-Revision-1.4-2025.08.01-Ratified.pdf"
            pages: 59
          test_plans:
            - name: "ZNS Command Set Conformance"
              file: "testplans/nvme/2.0/UNH-IOL_NVMe_ZNS_Command_Set_Conformance_v23.0_2025.01.19.pdf"
              version: "23.0"
              pages: 148

# Example 2: Ethernet with versions
ethernet:
  category: "networking"
  description: "Ethernet standards and test plans"
  
  versions:
    "1G":
      specs:
        - name: "IEEE 802.3ab-1999 (1000BASE-T)"
          file: "specs/ethernet/1G/802.3ab-1999.pdf"
          standard: "IEEE 802.3ab"
      test_plans:
        - name: "1000BASE-T PMA Test Suite"
          file: "testplans/ethernet/1G/1000BASE-T_PMA_Test_Suite_v2.6.pdf"
          version: "2.6"
          pages: 83
    
    "2.5G-5G":
      specs:
        - name: "IEEE 802.3bz-2016 (2.5G/5GBASE-T)"
          file: "specs/ethernet/2.5G-5G/802.3bz-2016.pdf"
          standard: "IEEE 802.3bz"
      test_plans:
        - name: "2.5G/5G PMA Test Plan"
          file: "testplans/ethernet/2.5G-5G/2.5G_5G_PMA_Test_Plan_v1.4.pdf"
          version: "1.4"
          pages: 24
    
    "10G":
      specs:
        - name: "IEEE 802.3ae-2002 (10 Gigabit)"
          file: "specs/ethernet/10G/802.3ae-2002.pdf"
          standard: "IEEE 802.3ae"
      test_plans:
        - name: "10GBASE-T Test Suite"
          file: "testplans/ethernet/10G/10GBASE-T_Test_Suite_v1.0.pdf"
          version: "1.0"

# Example 3: IPv6 with versions
ipv6:
  category: "networking"
  description: "IPv6 protocol specifications and test plans"
  
  versions:
    "core":
      specs:
        - name: "RFC 8200 - IPv6 Specification"
          file: "specs/ipv6/core/RFC8200_IPv6_Specification.txt"
          standard: "IETF RFC 8200"
      test_plans:
        - name: "IPv6 Core Protocols Conformance"
          file: "testplans/ipv6/core/IPv6_Core_Protocols_Conformance_v5.0.0.pdf"
          version: "5.0.0"
    
    "dhcpv6":
      specs:
        - name: "RFC 8415 - DHCPv6"
          file: "specs/ipv6/dhcpv6/RFC8415_DHCPv6.txt"
          standard: "IETF RFC 8415"
      test_plans:
        - name: "DHCPv6 Conformance"
          file: "testplans/ipv6/dhcpv6/DHCPv6_Conformance.pdf"

# Alternative approach: Using a simpler version suffix
usb:
  category: "connectivity"
  description: "USB standards and test plans"
  
  specs:
    - name: "USB Type-C Specification"
      versions:
        - version: "1.4"
          file: "specs/usb/USB_Type-C_Spec_R1.4.pdf"
          ratified: "2019-03-29"
          pages: 348
        - version: "2.0"
          file: "specs/usb/USB_Type-C_Spec_R2.0.pdf"
          ratified: "2019-08-29"
          pages: 373
        - version: "2.3"
          file: "specs/usb/USB_Type-C_Spec_R2.3.pdf"
          ratified: "2023-05-20"
          pages: 392
    
    - name: "USB Power Delivery"
      versions:
        - version: "2.0 v1.3"
          file: "specs/usb/USB_PD_R2.0_V1.3.pdf"
          pages: 214
        - version: "3.0 v1.1"
          file: "specs/usb/USB_PD_R3.0_V1.1.pdf"
          pages: 329
        - version: "3.1 v1.3"
          file: "specs/usb/USB_PD_R3.1_V1.3.pdf"
          pages: 346
  
  test_plans:
    - name: "USB Type-C Compliance"
      versions:
        - version: "2.1b"
          file: "testplans/usb/USB_Type-C_Compliance_Document_Rev_2_1b_June_2021.pdf"
          date: "2021-06-01"
          pages: 86
        - version: "2.2"
          file: "testplans/usb/USB_Type-C_Compliance_Document_Rev_2_2_Oct_2023.pdf"
          date: "2023-10-01"
          pages: 92
    
    - name: "USB PD Compliance Test"
      versions:
        - version: "PD2 CTS r1.1"
          file: "testplans/usb/USB_PD2_CTS_r1.1.pdf"
          pages: 189
        - version: "PD3 CTS r1.4 V5"
          file: "testplans/usb/USB_PD3_CTS_r1.4_V5_OR.pdf"
          pages: 301

# Directory structure recommendation:
directories:
  specs: "Specification documents organized by technology/version"
  testplans: "Test plans organized by technology/version"
  
  structure_example: |
    specs/
    ├── nvme/
    │   ├── 1.3/
    │   ├── 1.4/
    │   └── 2.0/
    ├── ethernet/
    │   ├── 1G/
    │   ├── 2.5G-5G/
    │   └── 10G/
    └── usb/
        ├── type-c-1.4/
        ├── type-c-2.0/
        └── pd-3.1/
    
    testplans/
    ├── nvme/
    │   ├── 1.3/
    │   ├── 1.4/
    │   └── 2.0/
    └── ...